[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_16MB.csv

extra_scripts = pre:remove_helium.py

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -Wno-unused-variable
    -Wno-unused-function

lib_deps =
    lvgl/lvgl @ 9.1.0
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    beegee-tokyo/DHT sensor library for ESPx @ ^1.0.0
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.0
    arduino-libraries/Ethernet @ ^2.0.2
    nrf24/RF24 @ ^1.4.8
    lsatan/SmartRC-CC1101-Driver-Lib @ ^3.0.2
